language: php
php:
    - "5.4"
    - "5.3"

notifications:
  email: false

before_script:
    - composer install --dev --prefer-source

script:
    - "./vendor/bin/phpunit"
    - "./vendor/bin/behat --profile standalone"